name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 20
        uses: actions/setup-java@v1
        with:
          java-version: '20'
      - name: Docker compose
        run: docker-compose up -d
      - name: Sleeping
        run: sleep 30
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Github API URL
        run: echo ${GITHUB_API_URL}
      - name: Sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.host.url="https://sonarcloud.io" \
          -Dsonar.organization=memoria-io \
          -Dsonar.projectKey=memoria-io_reactive


#          -Dsonar.pullrequest.github.repository=${{ GITHUB_REPOSITORY }}
#          -Dsonar.pullrequest.branch=${{ GITHUB_HEAD_REF#refs/heads/ }}
#          -Dsonar.pullrequest.base=${{ GITHUB_BASE_REF#refs/heads/ }} \
#          -Dsonar.pullrequest.key=${{ github.event.number }}


